### ISSUE TITLE
Broken client.js code

### ISSUE THREAD

**Issue by justin-luoma** [ryanorsinger/ten-functions#6]
solutions-edit-link was removed from readme.html in commit [4fdf54f5abe4e81eea208109c7fdaa5b260e5964](https://github.com/ryanorsinger/ten-functions/commit/4fdf54f5abe4e81eea208109c7fdaa5b260e5964#diff-215b25d5bf5c0b4623ad1a2b62456f60) but client.js still has a reference to it causing javascript errors on the page.

**Comment by ryanorsinger** [comment]
Good fix. Thank you.
